#version 430 core
in vec2 local;
in vec3 radiance;
in float opacity;
in float distanceToEye;
in float emissiveFactor;
in float waterFactor;
in float vaporFactor;
in float trailFactor;
in vec3 directionToEye;
in vec4 shadowPosition;
in vec3 reflectionPosition;
uniform float atmosphereOpacity;
uniform float particleBrightness;
uniform bool opaquePass;
uniform vec3 sunDirection;
uniform float daylight;
uniform sampler2DArrayShadow terrainShadowMap;
uniform sampler2D reflectionTexture;
uniform mat4 reflectionViewProjection;
uniform float time;
uniform bool reflectionCapture;
layout(location = 0) out vec4 fragColor;
layout(location = 1) out vec4 emissiveColor;
float hazeTransmittance(float distanceToEye) {
    float distanceBeyondClearAir=max(distanceToEye-300.0,0.0);
    float opticalDepth=pow(distanceBeyondClearAir/1200.0,2.4)*atmosphereOpacity*0.025;
    return exp(-opticalDepth);
}
float sunVisibility() {
    vec3 p=shadowPosition.xyz/shadowPosition.w*0.5+0.5;
    if(any(lessThan(p,vec3(0.0))) || any(greaterThan(p,vec3(1.0)))) return 1.0;
    vec2 texel=1.0/vec2(textureSize(terrainShadowMap,0).xy);
    float visibility=0.0;
    float bias=0.0002;
    for(int y=-1;y<=1;++y) for(int x=-1;x<=1;++x)
        visibility+=texture(terrainShadowMap,vec4(p.xy+vec2(x,y)*texel,0.0,p.z-bias));
    return visibility/9.0;
}
float dielectricFresnel(float cosineIncident,float etaIncident,float etaTransmitted) {
    float sineTransmittedSquared=(etaIncident/etaTransmitted)*(etaIncident/etaTransmitted)
        *max(0.0,1.0-cosineIncident*cosineIncident);
    if(sineTransmittedSquared>=1.0) return 1.0;
    float cosineTransmitted=sqrt(max(0.0,1.0-sineTransmittedSquared));
    float perpendicular=(etaIncident*cosineIncident-etaTransmitted*cosineTransmitted)
        /(etaIncident*cosineIncident+etaTransmitted*cosineTransmitted);
    float parallel=(etaTransmitted*cosineIncident-etaIncident*cosineTransmitted)
        /(etaTransmitted*cosineIncident+etaIncident*cosineTransmitted);
    return 0.5*(perpendicular*perpendicular+parallel*parallel);
}
void main() {
    float r2 = dot(local, local);
    float coverage = 1.0 - smoothstep(1.0 - max(fwidth(r2), 0.001), 1.0, r2);
    if(r2 > 1.0) discard;
    float haze = hazeTransmittance(distanceToEye);
    // Compact emissive disk only. Glow is generated by the HDR bloom pass.
    vec3 emission = radiance * 150.0 * particleBrightness * emissiveFactor;
    vec3 surfaceColor=mix(radiance,emission,emissiveFactor);
    float interfaceOpacity=1.0;
    if(waterFactor>0.5) {
        float shadowVisibility=sunVisibility();
        float localDaylight=daylight*shadowVisibility;
        vec3 normal=vec3(0.0,1.0,0.0);
        vec3 viewDirection=directionToEye/max(length(directionToEye),0.0001);
        vec3 reflection=reflect(-viewDirection,normal);
        float skyHeight=smoothstep(-0.15,0.85,reflection.y);
        vec3 reflectedSky=mix(vec3(0.34,0.52,0.72),vec3(0.055,0.24,0.62),skyHeight)*localDaylight;
        if(!reflectionCapture) {
            // Approximate reflected scenery at a fixed distance, allowing elevated
            // particles to use the ocean capture with an approximate parallax shift.
            const float proxyDistance=600.0;
            vec3 reflectedTarget=reflectionPosition+reflection*proxyDistance;
            vec4 reflectedClip=reflectionViewProjection*vec4(reflectedTarget,1.0);
            vec2 reflectionUv=reflectedClip.xy/max(abs(reflectedClip.w),0.0001)*0.5+0.5;
            vec2 ripple=vec2(sin(reflectionPosition.x*0.045+time*0.7),cos(reflectionPosition.z*0.052+time*0.58))*0.0025;
            reflectionUv+=ripple;
            float edge=min(min(reflectionUv.x,reflectionUv.y),min(1.0-reflectionUv.x,1.0-reflectionUv.y));
            float reflectionLighting=mix(1.0,shadowVisibility,daylight);
            float inside=smoothstep(0.0,0.025,edge)*step(0.0001,reflectedClip.w)*reflectionLighting;
            vec3 planarReflection=texture(reflectionTexture,clamp(reflectionUv,vec2(0.001),vec2(0.999))).rgb;
            reflectedSky=mix(reflectedSky,planarReflection,inside);
        }
        bool viewedFromAir=viewDirection.y>=0.0;
        float facing=abs(dot(normal,viewDirection));
        float fresnel=dielectricFresnel(facing,viewedFromAir?1.0:1.333,viewedFromAir?1.333:1.0);
        float sunGlint=pow(max(dot(reflection,sunDirection),0.0),180.0)*localDaylight;
        vec3 reflectedRadiance=reflectedSky+vec3(1.0,0.88,0.62)*sunGlint*2.5;
        // A particle represents a much thinner water volume than the water plane.
        float transmission=exp(-0.38/max(facing,0.08));
        vec3 waterScattering=mix(vec3(0.001,0.006,0.012),vec3(0.025,0.24,0.46),localDaylight);
        interfaceOpacity=1.0-(1.0-fresnel)*transmission;
        surfaceColor=(fresnel*reflectedRadiance
            +(1.0-fresnel)*(1.0-transmission)*waterScattering)/max(interfaceOpacity,0.0001);
    }
    if(vaporFactor>0.5) {
        float illumination=mix(0.025,0.18+0.82*sunVisibility(),daylight);
        surfaceColor*=illumination;
    }
    float softParticle=max(vaporFactor,trailFactor);
    float radialOpacity=mix(1.0,pow(max(1.0-r2,0.0),1.5),softParticle);
    float fragmentOpacity=coverage*opacity*radialOpacity*interfaceOpacity;
    if(opaquePass) fragColor = vec4(surfaceColor * opacity * haze, 1.0);
    else fragColor = vec4(surfaceColor, fragmentOpacity * haze);
    emissiveColor = vec4(emission * fragmentOpacity, fragmentOpacity);
}
