#version 430 core
in vec2 local;
in vec3 radiance;
in float opacity;
in float distanceToEye;
in float emissiveFactor;
in float waterFactor;
in float vaporFactor;
in vec3 directionToEye;
in vec4 shadowPosition;
uniform float atmosphereOpacity;
uniform float particleBrightness;
uniform bool opaquePass;
uniform vec3 sunDirection;
uniform float daylight;
uniform sampler2DArrayShadow terrainShadowMap;
layout(location = 0) out vec4 fragColor;
layout(location = 1) out vec4 emissiveColor;
float hazeTransmittance(float distanceToEye) {
    float distanceBeyondClearAir=max(distanceToEye-300.0,0.0);
    float opticalDepth=pow(distanceBeyondClearAir/1200.0,2.4)*atmosphereOpacity;
    return exp(-opticalDepth);
}
float sunVisibility() {
    vec3 p=shadowPosition.xyz/shadowPosition.w*0.5+0.5;
    if(any(lessThan(p,vec3(0.0))) || any(greaterThan(p,vec3(1.0)))) return 1.0;
    vec2 texel=1.0/vec2(textureSize(terrainShadowMap,0).xy);
    float visibility=0.0;
    float bias=0.0002;
    for(int y=-1;y<=1;++y) for(int x=-1;x<=1;++x)
        visibility+=texture(terrainShadowMap,vec4(p.xy+vec2(x,y)*texel,0.0,p.z-bias));
    return visibility/9.0;
}
void main() {
    float r2 = dot(local, local);
    float coverage = 1.0 - smoothstep(1.0 - max(fwidth(r2), 0.001), 1.0, r2);
    if(r2 > 1.0) discard;
    float haze = hazeTransmittance(distanceToEye);
    // Compact emissive disk only. Glow is generated by the HDR bloom pass.
    vec3 emission = radiance * 150.0 * particleBrightness * emissiveFactor;
    vec3 surfaceColor=mix(radiance,emission,emissiveFactor);
    if(waterFactor>0.5) {
        vec3 normal=vec3(0.0,1.0,0.0);
        vec3 reflection=reflect(-directionToEye,normal);
        float skyHeight=smoothstep(-0.15,0.85,reflection.y);
        vec3 reflectedSky=mix(vec3(0.34,0.52,0.72),vec3(0.055,0.24,0.62),skyHeight)*daylight;
        float facing=max(dot(normal,directionToEye),0.0);
        float fresnel=0.02+0.98*pow(1.0-facing,5.0);
        float sunGlint=pow(max(dot(reflection,sunDirection),0.0),180.0)*daylight;
        surfaceColor=radiance+reflectedSky*(0.16+0.84*fresnel)+vec3(1.0,0.88,0.62)*sunGlint*2.5;
    }
    if(vaporFactor>0.5) {
        float illumination=mix(0.025,0.18+0.82*sunVisibility(),daylight);
        surfaceColor*=illumination;
    }
    float radialOpacity=mix(1.0,pow(max(1.0-r2,0.0),1.5),vaporFactor);
    float fragmentOpacity=coverage*opacity*radialOpacity;
    if(opaquePass) fragColor = vec4(surfaceColor * opacity * haze, 1.0);
    else fragColor = vec4(surfaceColor, fragmentOpacity * haze);
    emissiveColor = vec4(emission * fragmentOpacity, fragmentOpacity);
}
